#!/bin/bash 
DBG_OPTION=""
TOOLCHAIN_OPTION=""
HMI_OPTION=""
MEDIA_OPTION="-DEXTENDED_MEDIA_MODE=OFF"
if [ $DEBUG ] && [ $DEBUG = "DBG_OFF" ]; then
     DBG_OPTION="-DCMAKE_BUILD_TYPE=Release"
fi
if [ $OS_TYPE ] && [ $OS_TYPE = "QNX" ]; then
     TOOLCHAIN_OPTION="-DCMAKE_TOOLCHAIN_FILE=./qnx_6.5.0_linux_x86.cmake"
fi
if [ $HMI_TYPE ] && [ $HMI_TYPE != "HTML5" ]; then
     HMI_OPTION="-DHMI2=ON"
fi
if [ $MEDIA_MODE ] && [ $MEDIA_MODE != "EXTENDED_MEDIA" ]; then
     MEDIA_OPTION="-DEXTENDED_MEDIA_MODE=ON"
fi

echo cmake ${DBG_OPTION} ${TOOLCHAIN_OPTION} ${HMI_OPTION} ${MEDIA_OPTION} -DBUILD_TESTS=On .
cmake ${DBG_OPTION} ${TOOLCHAIN_OPTION} ${HMI_OPTION} ${MEDIA_OPTION} -DBUILD_TESTS=On .
make install 
