
include(GNUInstallDirs)

if(QNXNTO)
  set(SDL_CONFIG_INSTALL_DIR "${CMAKE_INSTALL_SYSCONFDIR}/AppLink")
  set(SDL_PLUGINS_INSTALL_DIR "${CMAKE_INSTALL_SYSCONFDIR}/AppLink/plugins")
else()
  set(SDL_CONFIG_INSTALL_DIR "${CMAKE_INSTALL_BINDIR}")
  set(SDL_PLUGINS_INSTALL_DIR "${CMAKE_INSTALL_BINDIR}")
  set(CMAKE_INSTALL_LIBDIR "${CMAKE_INSTALL_BINDIR}")
endif()

