
include(GNUInstallDirs)



set(THIRD_PARTY_INSTALL_PREFIX "$ENV{THIRD_PARTY_INSTALL_PREFIX}")
message(STATUS "THIRD_PARTY_INSTALL_PREFIX: ${THIRD_PARTY_INSTALL_PREFIX}")

if (QNXNTO)
  set(CMAKE_FIND_ROOT_PATH "${CMAKE_FIND_ROOT_PATH}" "${THIRD_PARTY_INSTALL_PREFIX}")
endif()

set(BOOST_INCLUDEDIR "${THIRD_PARTY_INSTALL_PREFIX}/include")
set(BOOST_LIBRARYDIR "${THIRD_PARTY_INSTALL_PREFIX}/lib")

if(QNXNTO)
  set(SDL_CONFIG_INSTALL_DIR "${CMAKE_INSTALL_SYSCONFDIR}/AppLink")
  set(SDL_PLUGINS_INSTALL_DIR "${CMAKE_INSTALL_SYSCONFDIR}/AppLink/plugins")
else()
  set(SDL_CONFIG_INSTALL_DIR "${CMAKE_INSTALL_BINDIR}")
  set(SDL_PLUGINS_INSTALL_DIR "${CMAKE_INSTALL_BINDIR}")
  set(CMAKE_INSTALL_LIBDIR "${CMAKE_INSTALL_BINDIR}")
endif()

