/*                                           
 * 
 * @name AppLink Core 
 * 
 * @desc AppLink Core functionality
 * 
 * @category    HMI
 * @version 1.0
 *
 * @author  Sergey Solovey
 *
 */

 interface RPC2Communication::AppLinkCore;

version "1.2";

using AppLinkRPC;

prefix "AppLinkCore.";

#if 0
/*
 The only currently supported Json RPC version is 2.0
*/

envelope "JSON-RPC 2.0";

// The following is for RPCBus controller:
//serviceUrl "/localhost:6087";

#endif

/*
     * @descr 
     *     this methos is usually invoked by HMI to get list of registered apps 
     *  
     *  
     * @returns
     *      the array of rehgistered apps
     *  
     */
//TODO: specify return value.     
GetAppList(
    ->
    { string(100) appName, string(100) * ngnMediaScreenAppName, string * icon } appList []
    );

/*
     * @descr 
     *      Activate app 
     *  Usually invoked by UI component when user click on app in the list of registered apps
     *  
     * @returns
     *      result
     *  
     */ 
ActivateApp(
    string(100) appName 
    -> // return value is provided in corresponding response object, id of request and response should be equal
);

/*
     * @descr Notifies if new application is registered
     */
oneway OnAppRegistered(
    string(100) appName,
    string appIcon,
    string deviceName,
    string(40) * vrSynonym[1:100], // sysnonyms assossiated with app to start it
    bool isMediaApplication,
    Language languageDesired  // data type from AppLink protocol specification
);

/*
     * @descr Notifies if application is unregistered
     */
oneway OnAppUnregistered(
    string(100) appName,
    AppInterfaceUnregisteredReason * reason  // data type from AppLink protocol specification
);