/*
 * 
 * @name VR
 * 
 * @desc Voice Recognition functionality
 * 
 * @category    HMI
 * @version 1.0
 *
 * @author  
 *
 */
 interface RPC2Communication::VR;

 version "1.2";

 using AppLinkRPC;

prefix "VR.";

#if 0
/*
 The only currently supported Json RPC version is 2.0
*/

envelope "JSON-RPC 2.0";

// The following is for RPCBus controller:
//serviceUrl "/localhost:6087";

#endif

/*
     * @descr 
     *      method should be invoked at system startup
     *  provides information about voice recognition capabilities
     *  
     * @returns
     *      VR capabilites
     */ 
GetCapabilities(
    ->
    VrCapabilities capabilities[1:100] // data type from AppLink protocol specification
);

/*
     * @descr 
     *      add new command to VR
     *  
     * @returns
     *  result code
     */ 
AddCommand(
    unsigned int (2000000000) cmdId, // cmdID from addCommand request in AppLink protocol
    string (99) vrCommands [1:100] //An array of strings to be used as VR sysnonyms for this command
    -> ); // return value is provided in corresponding response object, id of request and response should be equal

/*
     * @descr 
     *      delete commands from VR
     *  
     * @returns
     *  result code
     */ 
DeleteCommand(
    unsigned int (2000000000) cmdId // cmdID from addCommand request in AppLink protocol
    -> ); // return value is provided in corresponding response object, id of request and response should be equal

/*
     * @descr Notifies AppLink core about command trigerred by VR
     */
oneway OnCommand(
    unsigned int (2000000000) cmdID // id of triggered command
    );

/*
"id": "integer" //REQUIRED for request methods. NOT to be used for notifications
*/