%language=C++
%struct-type
%define lookup-function-name getPointer
%define class-name Marshaller_intHash
%omit-struct-type
%readonly-tables
%compare-strncmp
%compare-lengths

struct Marshaller::localHash
{
  const char *name;
  unsigned int idx;
  void* method;
};

%%
AppLinkCore.ActivateApp,0,&Marshaller::mNsRPC2Communication_AppLinkCore__ActivateApp
AppLinkCore.ActivateAppResponse,1,&Marshaller::mNsRPC2Communication_AppLinkCore__ActivateAppResponse
AppLinkCore.GetAppList,2,&Marshaller::mNsRPC2Communication_AppLinkCore__GetAppList
AppLinkCore.GetAppListResponse,3,&Marshaller::mNsRPC2Communication_AppLinkCore__GetAppListResponse
AppLinkCore.OnAppRegistered,4,&Marshaller::mNsRPC2Communication_AppLinkCore__OnAppRegistered
AppLinkCore.OnAppUnregistered,5,&Marshaller::mNsRPC2Communication_AppLinkCore__OnAppUnregistered
AppLinkCore.SendData,6,&Marshaller::mNsRPC2Communication_AppLinkCore__SendData
AppLinkCore.SendDataResponse,7,&Marshaller::mNsRPC2Communication_AppLinkCore__SendDataResponse
Buttons.GetCapabilities,8,&Marshaller::mNsRPC2Communication_Buttons__GetCapabilities
Buttons.GetCapabilitiesResponse,9,&Marshaller::mNsRPC2Communication_Buttons__GetCapabilitiesResponse
Buttons.OnButtonEvent,10,&Marshaller::mNsRPC2Communication_Buttons__OnButtonEvent
Buttons.OnButtonPress,11,&Marshaller::mNsRPC2Communication_Buttons__OnButtonPress
TTS.GetCapabilities,12,&Marshaller::mNsRPC2Communication_TTS__GetCapabilities
TTS.GetCapabilitiesResponse,13,&Marshaller::mNsRPC2Communication_TTS__GetCapabilitiesResponse
TTS.Speak,14,&Marshaller::mNsRPC2Communication_TTS__Speak
TTS.SpeakResponse,15,&Marshaller::mNsRPC2Communication_TTS__SpeakResponse
UI.AddCommand,16,&Marshaller::mNsRPC2Communication_UI__AddCommand
UI.AddCommandResponse,17,&Marshaller::mNsRPC2Communication_UI__AddCommandResponse
UI.AddSubMenu,18,&Marshaller::mNsRPC2Communication_UI__AddSubMenu
UI.AddSubMenuResponse,19,&Marshaller::mNsRPC2Communication_UI__AddSubMenuResponse
UI.Alert,20,&Marshaller::mNsRPC2Communication_UI__Alert
UI.AlertResponse,21,&Marshaller::mNsRPC2Communication_UI__AlertResponse
UI.CreateInteractionChoiceSet,22,&Marshaller::mNsRPC2Communication_UI__CreateInteractionChoiceSet
UI.CreateInteractionChoiceSetResponse,23,&Marshaller::mNsRPC2Communication_UI__CreateInteractionChoiceSetResponse
UI.DeleteCommand,24,&Marshaller::mNsRPC2Communication_UI__DeleteCommand
UI.DeleteCommandResponse,25,&Marshaller::mNsRPC2Communication_UI__DeleteCommandResponse
UI.DeleteInteractionChoiceSet,26,&Marshaller::mNsRPC2Communication_UI__DeleteInteractionChoiceSet
UI.DeleteInteractionChoiceSetResponse,27,&Marshaller::mNsRPC2Communication_UI__DeleteInteractionChoiceSetResponse
UI.DeleteSubMenu,28,&Marshaller::mNsRPC2Communication_UI__DeleteSubMenu
UI.DeleteSubMenuResponse,29,&Marshaller::mNsRPC2Communication_UI__DeleteSubMenuResponse
UI.GetCapabilities,30,&Marshaller::mNsRPC2Communication_UI__GetCapabilities
UI.GetCapabilitiesResponse,31,&Marshaller::mNsRPC2Communication_UI__GetCapabilitiesResponse
UI.OnAppActivated,32,&Marshaller::mNsRPC2Communication_UI__OnAppActivated
UI.OnAppDeactivated,33,&Marshaller::mNsRPC2Communication_UI__OnAppDeactivated
UI.OnCommand,34,&Marshaller::mNsRPC2Communication_UI__OnCommand
UI.OnDriverDistraction,35,&Marshaller::mNsRPC2Communication_UI__OnDriverDistraction
UI.OnReady,36,&Marshaller::mNsRPC2Communication_UI__OnReady
UI.OnSystemContext,37,&Marshaller::mNsRPC2Communication_UI__OnSystemContext
UI.PerformInteraction,38,&Marshaller::mNsRPC2Communication_UI__PerformInteraction
UI.PerformInteractionResponse,39,&Marshaller::mNsRPC2Communication_UI__PerformInteractionResponse
UI.ResetGlobalProperties,40,&Marshaller::mNsRPC2Communication_UI__ResetGlobalProperties
UI.ResetGlobalPropertiesResponse,41,&Marshaller::mNsRPC2Communication_UI__ResetGlobalPropertiesResponse
UI.SetGlobalProperties,42,&Marshaller::mNsRPC2Communication_UI__SetGlobalProperties
UI.SetGlobalPropertiesResponse,43,&Marshaller::mNsRPC2Communication_UI__SetGlobalPropertiesResponse
UI.SetMediaClockTimer,44,&Marshaller::mNsRPC2Communication_UI__SetMediaClockTimer
UI.SetMediaClockTimerResponse,45,&Marshaller::mNsRPC2Communication_UI__SetMediaClockTimerResponse
UI.Show,46,&Marshaller::mNsRPC2Communication_UI__Show
UI.ShowResponse,47,&Marshaller::mNsRPC2Communication_UI__ShowResponse
VR.AddCommand,48,&Marshaller::mNsRPC2Communication_VR__AddCommand
VR.AddCommandResponse,49,&Marshaller::mNsRPC2Communication_VR__AddCommandResponse
VR.DeleteCommand,50,&Marshaller::mNsRPC2Communication_VR__DeleteCommand
VR.DeleteCommandResponse,51,&Marshaller::mNsRPC2Communication_VR__DeleteCommandResponse
VR.GetCapabilities,52,&Marshaller::mNsRPC2Communication_VR__GetCapabilities
VR.GetCapabilitiesResponse,53,&Marshaller::mNsRPC2Communication_VR__GetCapabilitiesResponse
VR.OnCommand,54,&Marshaller::mNsRPC2Communication_VR__OnCommand
