%language=C++
%struct-type
%define lookup-function-name getPointer
%define class-name Marshaller_intHash
%omit-struct-type
%readonly-tables
%compare-strncmp
%compare-lengths

struct NsRPC2Communication::Marshaller::localHash
{
  const char *name;
  unsigned int idx;
  void* method;
};

%%
AppLinkCore.ActivateApp,0,&NsRPC2Communication::Marshaller::mNsRPC2Communication_AppLinkCore__ActivateApp
AppLinkCore.ActivateAppResponse,1,&NsRPC2Communication::Marshaller::mNsRPC2Communication_AppLinkCore__ActivateAppResponse
AppLinkCore.GetAppList,2,&NsRPC2Communication::Marshaller::mNsRPC2Communication_AppLinkCore__GetAppList
AppLinkCore.GetAppListResponse,3,&NsRPC2Communication::Marshaller::mNsRPC2Communication_AppLinkCore__GetAppListResponse
AppLinkCore.OnAppRegistered,4,&NsRPC2Communication::Marshaller::mNsRPC2Communication_AppLinkCore__OnAppRegistered
AppLinkCore.OnAppUnregistered,5,&NsRPC2Communication::Marshaller::mNsRPC2Communication_AppLinkCore__OnAppUnregistered
AppLinkCore.SendData,6,&NsRPC2Communication::Marshaller::mNsRPC2Communication_AppLinkCore__SendData
AppLinkCore.SendDataResponse,7,&NsRPC2Communication::Marshaller::mNsRPC2Communication_AppLinkCore__SendDataResponse
Buttons.GetCapabilities,8,&NsRPC2Communication::Marshaller::mNsRPC2Communication_Buttons__GetCapabilities
Buttons.GetCapabilitiesResponse,9,&NsRPC2Communication::Marshaller::mNsRPC2Communication_Buttons__GetCapabilitiesResponse
Buttons.OnButtonEvent,10,&NsRPC2Communication::Marshaller::mNsRPC2Communication_Buttons__OnButtonEvent
Buttons.OnButtonPress,11,&NsRPC2Communication::Marshaller::mNsRPC2Communication_Buttons__OnButtonPress
TTS.GetCapabilities,12,&NsRPC2Communication::Marshaller::mNsRPC2Communication_TTS__GetCapabilities
TTS.GetCapabilitiesResponse,13,&NsRPC2Communication::Marshaller::mNsRPC2Communication_TTS__GetCapabilitiesResponse
TTS.Speak,14,&NsRPC2Communication::Marshaller::mNsRPC2Communication_TTS__Speak
TTS.SpeakResponse,15,&NsRPC2Communication::Marshaller::mNsRPC2Communication_TTS__SpeakResponse
UI.AddCommand,16,&NsRPC2Communication::Marshaller::mNsRPC2Communication_UI__AddCommand
UI.AddCommandResponse,17,&NsRPC2Communication::Marshaller::mNsRPC2Communication_UI__AddCommandResponse
UI.AddSubMenu,18,&NsRPC2Communication::Marshaller::mNsRPC2Communication_UI__AddSubMenu
UI.AddSubMenuResponse,19,&NsRPC2Communication::Marshaller::mNsRPC2Communication_UI__AddSubMenuResponse
UI.Alert,20,&NsRPC2Communication::Marshaller::mNsRPC2Communication_UI__Alert
UI.AlertResponse,21,&NsRPC2Communication::Marshaller::mNsRPC2Communication_UI__AlertResponse
UI.CreateInteractionChoiceSet,22,&NsRPC2Communication::Marshaller::mNsRPC2Communication_UI__CreateInteractionChoiceSet
UI.CreateInteractionChoiceSetResponse,23,&NsRPC2Communication::Marshaller::mNsRPC2Communication_UI__CreateInteractionChoiceSetResponse
UI.DeleteCommand,24,&NsRPC2Communication::Marshaller::mNsRPC2Communication_UI__DeleteCommand
UI.DeleteCommandResponse,25,&NsRPC2Communication::Marshaller::mNsRPC2Communication_UI__DeleteCommandResponse
UI.DeleteInteractionChoiceSet,26,&NsRPC2Communication::Marshaller::mNsRPC2Communication_UI__DeleteInteractionChoiceSet
UI.DeleteInteractionChoiceSetResponse,27,&NsRPC2Communication::Marshaller::mNsRPC2Communication_UI__DeleteInteractionChoiceSetResponse
UI.DeleteSubMenu,28,&NsRPC2Communication::Marshaller::mNsRPC2Communication_UI__DeleteSubMenu
UI.DeleteSubMenuResponse,29,&NsRPC2Communication::Marshaller::mNsRPC2Communication_UI__DeleteSubMenuResponse
UI.GetCapabilities,30,&NsRPC2Communication::Marshaller::mNsRPC2Communication_UI__GetCapabilities
UI.GetCapabilitiesResponse,31,&NsRPC2Communication::Marshaller::mNsRPC2Communication_UI__GetCapabilitiesResponse
UI.OnAppActivated,32,&NsRPC2Communication::Marshaller::mNsRPC2Communication_UI__OnAppActivated
UI.OnAppDeactivated,33,&NsRPC2Communication::Marshaller::mNsRPC2Communication_UI__OnAppDeactivated
UI.OnCommand,34,&NsRPC2Communication::Marshaller::mNsRPC2Communication_UI__OnCommand
UI.OnDriverDistraction,35,&NsRPC2Communication::Marshaller::mNsRPC2Communication_UI__OnDriverDistraction
UI.OnReady,36,&NsRPC2Communication::Marshaller::mNsRPC2Communication_UI__OnReady
UI.OnSystemContext,37,&NsRPC2Communication::Marshaller::mNsRPC2Communication_UI__OnSystemContext
UI.PerformInteraction,38,&NsRPC2Communication::Marshaller::mNsRPC2Communication_UI__PerformInteraction
UI.PerformInteractionResponse,39,&NsRPC2Communication::Marshaller::mNsRPC2Communication_UI__PerformInteractionResponse
UI.ResetGlobalProperties,40,&NsRPC2Communication::Marshaller::mNsRPC2Communication_UI__ResetGlobalProperties
UI.ResetGlobalPropertiesResponse,41,&NsRPC2Communication::Marshaller::mNsRPC2Communication_UI__ResetGlobalPropertiesResponse
UI.SetGlobalProperties,42,&NsRPC2Communication::Marshaller::mNsRPC2Communication_UI__SetGlobalProperties
UI.SetGlobalPropertiesResponse,43,&NsRPC2Communication::Marshaller::mNsRPC2Communication_UI__SetGlobalPropertiesResponse
UI.SetMediaClockTimer,44,&NsRPC2Communication::Marshaller::mNsRPC2Communication_UI__SetMediaClockTimer
UI.SetMediaClockTimerResponse,45,&NsRPC2Communication::Marshaller::mNsRPC2Communication_UI__SetMediaClockTimerResponse
UI.Show,46,&NsRPC2Communication::Marshaller::mNsRPC2Communication_UI__Show
UI.ShowResponse,47,&NsRPC2Communication::Marshaller::mNsRPC2Communication_UI__ShowResponse
VR.AddCommand,48,&NsRPC2Communication::Marshaller::mNsRPC2Communication_VR__AddCommand
VR.AddCommandResponse,49,&NsRPC2Communication::Marshaller::mNsRPC2Communication_VR__AddCommandResponse
VR.DeleteCommand,50,&NsRPC2Communication::Marshaller::mNsRPC2Communication_VR__DeleteCommand
VR.DeleteCommandResponse,51,&NsRPC2Communication::Marshaller::mNsRPC2Communication_VR__DeleteCommandResponse
VR.GetCapabilities,52,&NsRPC2Communication::Marshaller::mNsRPC2Communication_VR__GetCapabilities
VR.GetCapabilitiesResponse,53,&NsRPC2Communication::Marshaller::mNsRPC2Communication_VR__GetCapabilitiesResponse
VR.OnCommand,54,&NsRPC2Communication::Marshaller::mNsRPC2Communication_VR__OnCommand
