package com.ford.syncV4.proxy.rpc.enums;

public enum VehicleDataType {
	VEHICLEDATA_GPS,
	VEHICLEDATA_SPEED,
	VEHICLEDATA_FUELLEVEL,
	VEHICLEDATA_FUELECONOMY,
	VEHICLEDATA_ENGINERPM,
	VEHICLEDATA_BATTVOLTS,
	VEHICLEDATA_RAINSENSOR,
	VEHICLEDATA_ODOMETER,
	VEHICLEDATA_VIN,
	VEHICLEDATA_EXTERNTEMP,
	VEHICLEDATA_PRNDLSTATUS,
	VEHICLEDATA_TIREPRESSURE,
	VEHICLEDATA_BATTERYPACKVOLTAGE,
	VEHICLEDATA_BATTERYCURRENT,
	VEHICLEDATA_BATTERYTEMPERATURE,
	VEHICLEDATA_SATESN;

    public static VehicleDataType valueForString(String value) {
        return valueOf(value);
    }
}
