platform :ios, '4.3'

pod 'CocoaLumberjack',  '1.6'
pod 'JSONKit',          '1.5pre'
pod 'CocoaAsyncSocket', '7.2.2'
pod 'Reachability',     '3.1.1'

target :test do
    pod 'GHUnitIOS',    '0.5.5'
    pod 'OCMock',       '2.0.1'
end

# Dirty Hack! Don't Look Here!
#
# If you're reading this nevertheless, the post install hook
# add certain compiler flags for JSONKit files so that they won't
# generate warnings. This had been done in the podspec before, but
# was removed later for some reason.
#
# Author: Eugene Nikolsky
post_install do |installer|
    # Adds the specified compiler flags to the given file in the project.
    #
    # @param [Xcodeproj::Project] project
    #                             The Xcode project instance.
    #
    # @param [String] filename
    #                 The name of the file to work with.
    #
    # @param [String] new_compiler_flags
    #                 The compiler flags to add.
    #
    # @example Disable some warning switches for JSONKit:
    #   add_compiler_flags(installer.project,
    #       "JSONKit.m",
    #       "-Wno-deprecated-objc-isa-usage -Wno-format")
    #
    def add_compiler_flags(project, filename, new_compiler_flags)
        # find all PBXFileReference objects of the given file
        files = project.files().select { |file|
            file.display_name() == filename
        }

        # get the PBXBuildFile references of the found files
        # PBXBuildFile actually contains flags for building the file
        build_files = files.map { |file|
            file.build_files()
        }.compact.flatten

        # compiler flags key in settings
        compiler_flags_key = "COMPILER_FLAGS"

        if build_files.length > 0
            build_files.each {|build_file|
                settings = build_file.settings
                if settings.nil?
                    settings = Hash[compiler_flags_key, new_compiler_flags]
                else
                    compiler_flags = settings[compiler_flags_key]
                    compiler_flags = (compiler_flags.nil?) ?
                        new_compiler_flags :
                        (compiler_flags + " " + new_compiler_flags)
                    settings[compiler_flags_key] = compiler_flags
                end
                build_file.settings = settings
            }
        else
            puts "No build file refs found for #{filename}!"
        end
    end

    # compiler flags that turn off the JSONKit's warnings
    JSONKIT_FLAGS = "-Wno-deprecated-objc-isa-usage -Wno-format"
    add_compiler_flags(installer.project, "JSONKit.m", JSONKIT_FLAGS)
end

